CREATE TYPE "RideRole" AS ENUM (
	'Organizer',
	'Member'
);

CREATE TYPE "RideStatus" AS ENUM (
	'Open',
	'Full',
	'Cancelled',
	'Completed'
);

CREATE TABLE IF NOT EXISTS "User" (
	"id" UUID NOT NULL,
	"Username" VARCHAR(50) NOT NULL UNIQUE,
	"Email" VARCHAR(255) NOT NULL UNIQUE,
	"PasswordHash" TEXT NOT NULL,
	"FirstName" VARCHAR(50) NOT NULL,
	"LastName" VARCHAR(50) NOT NULL,
	"ProfilePictureUrl" TEXT,
	"Bio" TEXT,
	"CreatedAt" TIMESTAMPTZ NOT NULL,
	"UpdatedAt" TIMESTAMPTZ NOT NULL,
	"LastLoginAt" TIMESTAMPTZ,
	"IsVerified" BOOLEAN NOT NULL,
	"IsActive" BOOLEAN NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "UserMotorcycle" (
	"id" UUID NOT NULL,
	"ManufacturerId" UUID NOT NULL,
	"Model" VARCHAR(255) NOT NULL,
	"Color" VARCHAR(255),
	"Year" INTEGER NOT NULL,
	"OwnerId" UUID NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Manufacturer" (
	"id" UUID NOT NULL,
	"Name" VARCHAR(255) NOT NULL,
	"Country" VARCHAR(255) NOT NULL,
	"LogoUrl" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "RideRequest" (
	"id" UUID NOT NULL,
	"CreatorId" UUID NOT NULL,
	"Title" VARCHAR(255) NOT NULL,
	"Description" TEXT,
	"Status" RIDESTATUS NOT NULL,
	"Location" TEXT NOT NULL,
	"MaxParticipants" INTEGER NOT NULL,
	"CreatedAt" TIMESTAMPTZ NOT NULL,
	"UpdatedAt" TIMESTAMPTZ NOT NULL,
	"StartsAt" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "RideParticipant" (
	"UserId" UUID NOT NULL,
	"RideId" UUID NOT NULL,
	"Role" RIDEROLE NOT NULL,
	"JoinedAt" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("UserId", "RideId")
);



ALTER TABLE "UserMotorcycle"
ADD FOREIGN KEY("ManufacturerId") REFERENCES "Manufacturer"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserMotorcycle"
ADD FOREIGN KEY("OwnerId") REFERENCES "User"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "RideRequest"
ADD FOREIGN KEY("CreatorId") REFERENCES "User"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "RideParticipant"
ADD FOREIGN KEY("UserId") REFERENCES "User"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "RideParticipant"
ADD FOREIGN KEY("RideId") REFERENCES "RideRequest"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;